# Name of the workflow
name: Daily Sports Data Update

# Trigger conditions
on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

# Required permissions for the workflow
permissions:
  contents: write  # Needed for committing changes

jobs:
  should-run:
    runs-on: ubuntu-latest
    outputs:
      should_execute: ${{ steps.check.outputs.should_execute }}
    steps:
      - name: Check if we should run
        id: check
        run: |
          # Generate random number between 1 and 100
          # We want truly random runs, so we'll use a probability of ~5%
          if [ $((RANDOM % 20)) -eq 0 ]; then
            echo "should_execute=true" >> $GITHUB_OUTPUT
          else
            echo "should_execute=false" >> $GITHUB_OUTPUT
          fi

  update-sports-data:
    needs: should-run
    if: needs.should-run.outputs.should_execute == 'true'
    runs-on: ubuntu-latest  # Latest Ubuntu runner
    
    steps:
    # Checkout the repository with full history
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper versioning
    
    # Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Specify exact Python version
        
    # Install project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Run the update script
    - name: Run sports data update script
      run: python src/fetch_nba_data.py
        
    # Commit and push any changes
    - name: Commit and push changes
      run: |
        # Configure Git
        git config --local user.email "tstanmay13@gmail.com"
        git config --local user.name "tstanmay13"
        
        # Add all changes
        git add .
        
        # Get current time in ETC
        ETC_TIME=$(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S %Z')
        
        # Only commit if there are changes
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update sports data at $ETC_TIME"
        
        # Pull latest changes and rebase
        git pull --rebase
        
        # Push changes to main branch
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 